version: '3'

networks:
  prestanet:
  
volumes:
  postgres:




# Define the services/containers to be run
services:
  app:
    build:
      context: ./presta-web
      args:
        env: ${env}
    ports:
      - "80:8080"
    networks:
      prestanet:

  server: # name of the first service
    build: ./presta-api # specify the directory of the Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: presta_postgres
    image: "postgres:14"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes:
        - postgres:/data/postgres
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
  